CREATE TABLE [dbo].[AuthorBook]
(
	[BookId]	BIGINT NOT NULL,
	[AuthorId]	BIGINT NOT NULL,
	FOREIGN KEY (BookId) REFERENCES Books(Id) ON DELETE CASCADE,
	FOREIGN KEY (AuthorId) REFERENCES Authors(Id) ON DELETE CASCADE
)
